import type { Metadata } from 'next';
import { Volkhov, Poppins } from 'next/font/google';
import './globals.css';

const volkhov = Volkhov({
  subsets: ['latin'],
  weight: ['400'],
  display: 'swap',
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.className} ${volkhov.className}`}>
      <body>
        <main className="mx-auto">{children}</main>
      </body>
    </html>
  );
}
